#!/usr/bin/env bash
while true; do
cpu=$(eval $(awk '/^cpu /{print "previdle=" $5 "; prevtotal=" $2+$3+$4+$5 }' /proc/stat); sleep 0.4; eval $(awk '/^cpu /{print "idle=" $5 "; total=" $2+$3+$4+$5 }' /proc/stat); intervaltotal=$((total-${prevtotal:-0})); echo "$((100*( (intervaltotal) - ($idle-${previdle:-0}) ) / (intervaltotal) ))")
    #conky=$(conky -c /home/simon/.conkyrc)
    #tasks=$(top -b -n 1|awk '/Tasks/ {print $2}')
    gmail=$(head -n1 .gma1l)
    amixer=$(amixer get Master|tr -d "\n"|cut -d " " -f26)
    #    amixer=$(amixer get Master | awk '/Mono: Playback/ {print $4}')
    host=$(uptime | awk '{print $1" " $2" " $3" " $4}')
    ip=$(ifconfig tap0 |grep inet | grep -v inet6 |grep -v '127' | awk '{print $2}' |cut -d: -f2)
    home=$(df -h|awk '/root/ {print "/ " $5}')
    root=$(df -h|awk '/sdb4/ {print "/home " $5}')
    wireless=$(wireless_status|tail -n1)
    mem=$(free -m | awk '/buffers\/cache/ {print $3 MB}')
    # torrr=$(transmission-remote -l|awk '{print $5 " " $10}' |grep -v Up |grep -v 0.0)
    torr=$(transmission-remote -l | awk '/%/ {print $2 " "$11 " "$13 " " $14}'|tail -n1)
    #gcpu=$(gcpubar -bg black -w 30 -h 7 -fg "#D81860"|head -n1)
    irssi=$(head -n1 /home/simon/.logs/irssi_pipe)
    music=$(mpc current)
    [ -z "$music" ] && music="Stopped"
    date=$(date "+%R")
xsetroot -name "Cpu: $cpu Mem: $mem Mail: $gmail Alsa: $amixer - $host - $ip - Free: $home $root Wifi: $wireless Ul: $torr - $irssi - $music - $date"
done
